Update to CM 1.6 (#1209)
This updates the project to Compose Multiplatform 1.6.0.

**Changes**
- Fixed JS support to use `browser()` instead of NodeJS.
- Added toe-holds for WASM support. Can't add it until we get a molecule
WASM target.
- Misc changes along the way for the compose update itself.

**Followup work**
- Will need some work to migrate off swipeable
https://developer.android.com/jetpack/compose/touch-input/pointer-input/migrate-swipeable
- The new generated `Res` objects for resources don't actually seem to
work. Will file a report separately ¯\_(ツ)_/¯
- Kotlin JS/compose multiplatform on JS continues to be a mess. The
counter sample still doesn't run despite fixes here. Yields the
following obscure errors (on chrome and firefox respectively)

```
ClassCastException
    at THROW_CCE (webpack-internal:///../counterApp/kotlin/counterApp.js:9882:11)
    at protoOf.insertTopDown_7i64np_k$ (webpack-internal:///../counterApp/kotlin/counterApp.js:287811:96)
    at protoOf.execute_bg9gly_k$ (webpack-internal:///../counterApp/kotlin/counterApp.js:104648:17)
    at protoOf.executeAndFlushAllPendingOperations_me43h6_k$ (webpack-internal:///../counterApp/kotlin/counterApp.js:105781:44)
    at protoOf.executeAndFlushAllPendingFixups_o2eddv_k$ (webpack-internal:///../counterApp/kotlin/counterApp.js:103636:23)
    at protoOf.execute_bg9gly_k$ (webpack-internal:///../counterApp/kotlin/counterApp.js:104583:14)
    at protoOf.executeAndFlushAllPendingOperations_me43h6_k$ (webpack-internal:///../counterApp/kotlin/counterApp.js:105781:44)
    at protoOf.executeAndFlushAllPendingChanges_o7h1mb_k$ (webpack-internal:///../counterApp/kotlin/counterApp.js:101644:30)
    at applyChangesInLocked (webpack-internal:///../counterApp/kotlin/counterApp.js:89414:21)
    at protoOf.applyChanges_ynn7tn_k$ (webpack-internal:///../counterApp/kotlin/counterApp.js:90565:9)
```

```
Module["org_jetbrains_skia_paragraph_FontCollection__1nMake"] is not a function
```