Update dependency org.jetbrains.dokka to v1.8.10 (#481)
This PR contains the following updates:

| Package | Type | Update | Change |
|---|---|---|---|
| [org.jetbrains.dokka](https://togithub.com/Kotlin/dokka) | plugin |
minor | `1.7.20` -> `1.8.10` |

---

### Release Notes

<details>
<summary>Kotlin/dokka</summary>

### [`v1.8.10`](https://togithub.com/Kotlin/dokka/releases/tag/v1.8.10)

Dokka's documentation has been entirely rewritten and can now be found
on
[kotlinlang.org](https://kotlinlang.org/docs/dokka-introduction.html):

-   More examples, including Groovy DSL for Gradle project configuration
-   More guidelines to help beginners
-   More details for complex projects

**Note**: Version 1.8.0 was skipped due to a Metaspace memory leak in
Kotlin's reflection
([KT-56093](https://youtrack.jetbrains.com/issue/KT-56093)). Dokka
1.8.10 should be fully compatible with Kotlin 1.8.0.

#### Improvements

- Revise project documentation and examples
([#&#8203;2728](https://togithub.com/Kotlin/dokka/issues/2728),
[#&#8203;2737](https://togithub.com/Kotlin/dokka/issues/2737),
[#&#8203;2736](https://togithub.com/Kotlin/dokka/issues/2736)). Thanks
to [@&#8203;sarahhaggarty](https://togithub.com/sarahhaggarty) for
helping!
- Support generating documentation for Kotlin/Wasm projects
([#&#8203;2814](https://togithub.com/Kotlin/dokka/issues/2814)). Thanks
to [@&#8203;igoriakovlev](https://togithub.com/igoriakovlev)!
- Move the contents of `Inheritors`, `Parameters`, `See also` and
`Samples` tabs into the main declaration description
([#&#8203;2688](https://togithub.com/Kotlin/dokka/issues/2688)).
- Add `Members` and `Members & Extensions` tabs to class-like
declaration pages
([#&#8203;2764](https://togithub.com/Kotlin/dokka/issues/2764)).
- Display source set / platform indicators at all times, which should
help identify the supported platform of single-platform libraries and
modules.
([#&#8203;2847](https://togithub.com/Kotlin/dokka/issues/2847)).
- Generate the default no-arg constructor for Java declarations
([#&#8203;2765](https://togithub.com/Kotlin/dokka/issues/2765)).

#### Bugfixes

- Fixed analysis environment not being properly disposed
([#&#8203;2755](https://togithub.com/Kotlin/dokka/issues/2755)).
- Fixed nondeterministic sorting of function/property overloads
([#&#8203;2784](https://togithub.com/Kotlin/dokka/issues/2784)).
- Fixed inconsistent alphabetical order of element groups in index and
navigation
([#&#8203;2861](https://togithub.com/Kotlin/dokka/issues/2861)).
- Fixed constructors being rendered as functions
([#&#8203;2689](https://togithub.com/Kotlin/dokka/issues/2689)).
- Fixed default values for `var` properties being displayed
([#&#8203;2717](https://togithub.com/Kotlin/dokka/issues/2717)).
- Fixed source links leading to the KDoc instead of the declaration
([#&#8203;2724](https://togithub.com/Kotlin/dokka/issues/2724)).
- Fixed thread-safety issues in `DokkaLogger`
([#&#8203;2827](https://togithub.com/Kotlin/dokka/issues/2827)).
- Fixed documentation not being inherited in case of diamond inheritance
([#&#8203;2686](https://togithub.com/Kotlin/dokka/issues/2686)).

##### Gradle Plugin

- Fixed `NoSuchMethodError` when running under Gradle 8
([#&#8203;2796](https://togithub.com/Kotlin/dokka/issues/2796)).
- Fixed possible metaspace leaks due to external thread locals not being
disposed
([#&#8203;2678](https://togithub.com/Kotlin/dokka/issues/2678)).
- Fixed premature initialization of `outputDirectory` input property
([#&#8203;556](https://togithub.com/Kotlin/dokka/issues/556)).
- Fixed premature initialization of `moduleVersion` input property
([#&#8203;2799](https://togithub.com/Kotlin/dokka/issues/2799)). Thanks
to
[@&#8203;JavierSegoviaCordoba](https://togithub.com/JavierSegoviaCordoba)!
- Fixed unnecessary snapshotting of source link directory input which
led to performance problems
([#&#8203;2807](https://togithub.com/Kotlin/dokka/issues/2807)).
- Fixed missing group and description for `MultiModule` tasks
([#&#8203;2806](https://togithub.com/Kotlin/dokka/issues/2806)). Thanks
to [@&#8203;TWiStErRob](https://togithub.com/TWiStErRob)!

##### Javadoc

- Fixed truncation of module and package description after the first
sentence
([#&#8203;2055](https://togithub.com/Kotlin/dokka/issues/2055)). Thanks
to [@&#8203;BlackAnubis7](https://togithub.com/BlackAnubis7)!
- Fixed rendering of empty/useless Kotlin companion objects
([#&#8203;200](https://togithub.com/Kotlin/dokka/issues/200),
[#&#8203;2086](https://togithub.com/Kotlin/dokka/issues/2086))
- Fixed leaking configuration/environment details in generated links
([#&#8203;2803](https://togithub.com/Kotlin/dokka/issues/2803)).
- Fixed incorrect links when `javadoc.jar` produced by Dokka is imported
into IntelliJ IDEA / Android Studio
([#&#8203;2734](https://togithub.com/Kotlin/dokka/issues/2734)). Thanks
to [@&#8203;bomberaya](https://togithub.com/bomberaya)!

#### Plugin API

- Mark Plugin API as experimental
([#&#8203;2716](https://togithub.com/Kotlin/dokka/issues/2716)).

#### Infrastructure

- Enable Gradle build cache, and add caching of Maven dependencies for
GitHub Actions
([#&#8203;2711](https://togithub.com/Kotlin/dokka/issues/2711),
[#&#8203;2722](https://togithub.com/Kotlin/dokka/issues/2722)). Thanks
to [@&#8203;aSemy](https://togithub.com/aSemy)!
- Add concurrency cancellation for build/test GitHub Actions
([#&#8203;2710](https://togithub.com/Kotlin/dokka/issues/2710)). Thanks
to [@&#8203;aSemy](https://togithub.com/aSemy)!

#### Other

- Update `jackson-databind` to avoid CVE-2022-42003
([#&#8203;2733](https://togithub.com/Kotlin/dokka/issues/2733)). Thanks
to [@&#8203;ryanlewis](https://togithub.com/ryanlewis)!
- Update `Jsoup` to avoid CVE-2022-36033
([#&#8203;2772](https://togithub.com/Kotlin/dokka/issues/2772)).
- Deprecate methods for adding/removing task dependencies in Dokka's
Gradle plugin
([#&#8203;2857](https://togithub.com/Kotlin/dokka/issues/2857)).
- Documentation improvements and fixes
([#&#8203;2719](https://togithub.com/Kotlin/dokka/issues/2719),
[#&#8203;2718](https://togithub.com/Kotlin/dokka/issues/2718),
[#&#8203;2744](https://togithub.com/Kotlin/dokka/issues/2744)). Thanks
to [@&#8203;SimonMarquis](https://togithub.com/SimonMarquis) and
[@&#8203;ansman](https://togithub.com/ansman)!

</details>

---

### Configuration

📅 **Schedule**: Branch creation - At any time (no schedule defined),
Automerge - At any time (no schedule defined).

🚦 **Automerge**: Disabled by config. Please merge this manually once you
are satisfied.

♻ **Rebasing**: Whenever PR becomes conflicted, or you tick the
rebase/retry checkbox.

🔕 **Ignore**: Close this PR and you won't be reminded about this update
again.

---

- [ ] <!-- rebase-check -->If you want to rebase/retry this PR, click
this checkbox.

---

This PR has been generated by [Renovate
Bot](https://togithub.com/renovatebot/renovate).

<!--renovate-debug:eyJjcmVhdGVkSW5WZXIiOiIzMi4xOTAuNiIsInVwZGF0ZWRJblZlciI6IjMyLjE5MC42In0=-->