Update ktor monorepo to v2.3.12 (#1487)
This PR contains the following updates:

| Package | Type | Update | Change |
|---|---|---|---|
|
[io.ktor:ktor-serialization-kotlinx-json](https://togithub.com/ktorio/ktor)
| dependencies | patch | `2.3.11` -> `2.3.12` |
| [io.ktor:ktor-client-js](https://togithub.com/ktorio/ktor) |
dependencies | patch | `2.3.11` -> `2.3.12` |
| [io.ktor:ktor-client-auth](https://togithub.com/ktorio/ktor) |
dependencies | patch | `2.3.11` -> `2.3.12` |
| [io.ktor:ktor-client-okhttp](https://togithub.com/ktorio/ktor) |
dependencies | patch | `2.3.11` -> `2.3.12` |
|
[io.ktor:ktor-client-content-negotiation](https://togithub.com/ktorio/ktor)
| dependencies | patch | `2.3.11` -> `2.3.12` |
| [io.ktor:ktor-client-core](https://togithub.com/ktorio/ktor) |
dependencies | patch | `2.3.11` -> `2.3.12` |

---

> [!WARNING]
> Some dependencies could not be looked up. Check the Dependency
Dashboard for more information.

---

### Release Notes

<details>
<summary>ktorio/ktor (io.ktor:ktor-serialization-kotlinx-json)</summary>

### [`v2.3.12`](https://togithub.com/ktorio/ktor/releases/tag/2.3.12)

[Compare
Source](https://togithub.com/ktorio/ktor/compare/2.3.11...2.3.12)

> Published 20 June 2024

##### Bugfixes

- NoSuchMethodError when using coroutines 1.9.0-RC
([KTOR-7054](https://youtrack.jetbrains.com/issue/KTOR-7054))
- Server: Content-Type header for static js, css and svg resources
misses charset
([KTOR-6655](https://youtrack.jetbrains.com/issue/KTOR-6655))
- Embedded Linux device without iso-8859-1 and UTF-16 cannot use
ktor-network
([KTOR-7016](https://youtrack.jetbrains.com/issue/KTOR-7016))

##### Improvements

- Update netty to 4.1.111.Final
([KTOR-7094](https://youtrack.jetbrains.com/issue/KTOR-7094))
- Update netty due to CVE-2024-29025
([KTOR-7014](https://youtrack.jetbrains.com/issue/KTOR-7014))
- Update dependency on swagger
([KTOR-7019](https://youtrack.jetbrains.com/issue/KTOR-7019))

</details>

---

### Configuration

📅 **Schedule**: Branch creation - At any time (no schedule defined),
Automerge - At any time (no schedule defined).

🚦 **Automerge**: Enabled.

♻ **Rebasing**: Whenever PR becomes conflicted, or you tick the
rebase/retry checkbox.

🔕 **Ignore**: Close this PR and you won't be reminded about these
updates again.

---

- [ ] <!-- rebase-check -->If you want to rebase/retry this PR, check
this box

---

This PR has been generated by [Renovate
Bot](https://togithub.com/renovatebot/renovate).

<!--renovate-debug:eyJjcmVhdGVkSW5WZXIiOiIzNy40MTMuNCIsInVwZGF0ZWRJblZlciI6IjM3LjQxMy40IiwidGFyZ2V0QnJhbmNoIjoibWFpbiIsImxhYmVscyI6W119-->