Update dependency org.jetbrains.kotlinx:kotlinx-serialization-json-okio to v1.7.3 (#1671)
This PR contains the following updates:

| Package | Type | Update | Change |
|---|---|---|---|
|
[org.jetbrains.kotlinx:kotlinx-serialization-json-okio](https://redirect.github.com/Kotlin/kotlinx.serialization)
| dependencies | patch | `1.7.1` -> `1.7.3` |

---

> [!WARNING]
> Some dependencies could not be looked up. Check the Dependency
Dashboard for more information.

---

### Release Notes

<details>
<summary>Kotlin/kotlinx.serialization
(org.jetbrains.kotlinx:kotlinx-serialization-json-okio)</summary>

###
[`v1.7.3`](https://redirect.github.com/Kotlin/kotlinx.serialization/blob/HEAD/CHANGELOG.md#173--2024-09-19)

\==================

This release aims to fix important issues that were discovered in the
1.7.2 release,
including the inability to sync certain projects into Android
Studio/IntelliJ IDEA and exceptions from custom Uuid serializers.

It uses Kotlin 2.0.20 by default.

- Use explicit kotlin-stdlib and kotlin-test versions from version
catalog
([#&#8203;2818](https://redirect.github.com/Kotlin/kotlinx.serialization/issues/2818))
- Drop usage of deprecated Any?.freeze() in K/N target
([#&#8203;2819](https://redirect.github.com/Kotlin/kotlinx.serialization/issues/2819))
- Check against serialName instead of simpleClassName
([#&#8203;2802](https://redirect.github.com/Kotlin/kotlinx.serialization/issues/2802))
- Ignore NoClassDefFoundError when initializing builtins map for
serializer() function
([#&#8203;2803](https://redirect.github.com/Kotlin/kotlinx.serialization/issues/2803))
- Clarify example for SerializationException
([#&#8203;2806](https://redirect.github.com/Kotlin/kotlinx.serialization/issues/2806))

###
[`v1.7.2`](https://redirect.github.com/Kotlin/kotlinx.serialization/blob/HEAD/CHANGELOG.md#172--2024-08-28)

\==================

This release provides several new features, including a major Cbor
configuration rework.
It uses Kotlin 2.0.20 by default.

#### Cbor feature set for COSE compliance

This change brings a lot of features to the CBOR format, namely:

- Serial Labels — see `@CborLabel` annotation and
`preferCborLabelsOverNames` flag.
- Tagging of keys and values — see `encode*Tags` and `verify*Tags` set
of flags
- Definite length encoding — see `useDefiniteLengthEncoding`. This flag
affects object encoding, since decoding of arrays with definite lenghts
is automatically supported.
- Option to globally prefer major type 2 for byte array encoding — see
`alwaysUseByteString` flag.

Since there are quite a lot of flags now, they were restructured to a
separate `CborConfiguration` class, similarly to `JsonConfiguration`.
It is possible to retrieve this configuration from
`CborEncoder/CborDecoder` interfaces in your custom serializers (see
their documentation for details).

All of these features make it possible to serialize and parse
[COSE-compliant CBOR](https://datatracker.ietf.org/doc/html/rfc8152),
for example, ISO/IEC 18013-5:2021-compliant mobile driving license data.
In case you want to make use of them, there is a predefined
`Cbor.CoseCompliant` instance.
However, some canonicalization steps (such as sorting keys) still need
to be performed manually.

This functionality [was
contributed](https://redirect.github.com/Kotlin/kotlinx.serialization/pull/2412)
to us by [Bernd Prünster](https://redirect.github.com/JesusMcCloud).

#### Keeping generated serializers

One of the most requested features for serialization plugin was to
continue to generate a serializer even if a custom one is specified for
the class.
It allows using a plugin-generated serializer in a fallback or delegate
strategy, accessing type structure via descriptor, using default
serialization behavior in inheritors that do not use custom serializers.

Starting with this release, you can specify the
`@KeepGeneratedSerializer` annotation on the class declaration to
instruct the plugin to continue generating the serializer.
In this case, the serializer will be accessible using the
`.generatedSerializer()` function on the class's companion object.

> This annotation is currently experimental. Kotlin 2.0.20 or higher is
required for this feature to work.

You can check out the examples in [the
documentation](docs/serializers.md#simultaneous-use-of-plugin-generated-and-custom-serializers)
and in the PRs:
[#&#8203;2758](https://redirect.github.com/Kotlin/kotlinx.serialization/pull/2758),
[#&#8203;2669](https://redirect.github.com/Kotlin/kotlinx.serialization/pull/2669).

#### Serializer for kotlin.uuid.Uuid

Kotlin 2.0.20
[added](https://kotlinlang.org/docs/whatsnew2020.html#support-for-uuids-in-the-common-kotlin-standard-library)
a common class to represent UUIDs in a multiplatform code.
kotlinx.serialization 1.7.2 provides a corresponding `Uuid.serializer()`
for it, making it possible to use it in `@Serializable` classes.
Note that for now, serializer should be provided manually with
[`@Contextual`
annotation](https://redirect.github.com/Kotlin/kotlinx.serialization/blob/master/docs/serializers.md#contextual-serialization).
Plugin will be able to automatically insert `Uuid` serializer in Kotlin
2.1.0.

See more details in the [corresponding
PR](https://redirect.github.com/Kotlin/kotlinx.serialization/pull/2744).

#### Other bugfixes and improvements

- Prohibited using of zero and negative field numbers in ProtoNumber
([#&#8203;2766](https://redirect.github.com/Kotlin/kotlinx.serialization/issues/2766))
- Improve readability of protobuf decoding exception messages
([#&#8203;2768](https://redirect.github.com/Kotlin/kotlinx.serialization/issues/2768))
(thanks to
[xiaozhikang0916](https://redirect.github.com/xiaozhikang0916))
- docs(serializers): Fix grammatical errors
([#&#8203;2779](https://redirect.github.com/Kotlin/kotlinx.serialization/issues/2779))
(thanks to [jamhour1g](https://redirect.github.com/jamhour1g))
- Fixed VerifyError after ProGuard optimization
([#&#8203;2728](https://redirect.github.com/Kotlin/kotlinx.serialization/issues/2728))
- Add wasm-wasi target to Okio integration
([#&#8203;2727](https://redirect.github.com/Kotlin/kotlinx.serialization/issues/2727))

</details>

---

### Configuration

📅 **Schedule**: Branch creation - At any time (no schedule defined),
Automerge - At any time (no schedule defined).

🚦 **Automerge**: Enabled.

♻ **Rebasing**: Whenever PR becomes conflicted, or you tick the
rebase/retry checkbox.

🔕 **Ignore**: Close this PR and you won't be reminded about this update
again.

---

- [ ] <!-- rebase-check -->If you want to rebase/retry this PR, check
this box

---

This PR has been generated by [Renovate
Bot](https://redirect.github.com/renovatebot/renovate).

<!--renovate-debug:eyJjcmVhdGVkSW5WZXIiOiIzOC45MS4wIiwidXBkYXRlZEluVmVyIjoiMzguOTEuMCIsInRhcmdldEJyYW5jaCI6Im1haW4iLCJsYWJlbHMiOltdfQ==-->

---------

Co-authored-by: Josh Stagg <jstagg@slack-corp.com>